const LOGIN = 'LOGIN';
const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
const LOGOUT = 'LOGOUT';
const LOGIN_FAILED = 'LOGIN_FAILED';
const TRY_AGAIN = 'TRY_AGAIN';

export {
  LOGIN,
  LOGIN_SUCCESSFUL,
  LOGOUT,
  LOGIN_FAILED,
  TRY_AGAIN
}